// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrPePWNrWYwRulGZezzZ_GnldWez_ceJA',
    appId: '1:52908620727:android:e02847ad0796dc7ecbc632',
    messagingSenderId: '52908620727',
    projectId: 'studyhub-92581',
    storageBucket: 'studyhub-92581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKaBQYdCDPXZS56La5UknK4CNzmb6rld4',
    appId: '1:52908620727:ios:37119143a6677c6dcbc632',
    messagingSenderId: '52908620727',
    projectId: 'studyhub-92581',
    storageBucket: 'studyhub-92581.firebasestorage.app',
    iosBundleId: 'com.example.studyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKaBQYdCDPXZS56La5UknK4CNzmb6rld4',
    appId: '1:52908620727:ios:37119143a6677c6dcbc632',
    messagingSenderId: '52908620727',
    projectId: 'studyhub-92581',
    storageBucket: 'studyhub-92581.firebasestorage.app',
    iosBundleId: 'com.example.studyhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcVQYjFojrVgrKN138y3VFmV1gnvuUDcA',
    appId: '1:52908620727:web:51b6877e89797006cbc632',
    messagingSenderId: '52908620727',
    projectId: 'studyhub-92581',
    authDomain: 'studyhub-92581.firebaseapp.com',
    storageBucket: 'studyhub-92581.firebasestorage.app',
    measurementId: 'G-7BGP7J5FXN',
  );
}
